//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ItemsBaseData
    {
        public int ItemID { get; set; }
        public int CategoryID { get; set; }
        public int ModuleTypeID { get; set; }
        public string PhotoExtension { get; set; }
        public string Url { get; set; }
        public string Email { get; set; }
        public string MailBox { get; set; }
        public string ZipCode { get; set; }
        public string Tels { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public int Vistites_Count { get; set; }
        public System.DateTime Date_Added { get; set; }
        public Nullable<System.DateTime> ItemDate { get; set; }
        public Nullable<System.DateTime> ItemEndDate { get; set; }
        public bool IsAvailable { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public string Photo2Extension { get; set; }
        public string VideoExtension { get; set; }
        public string AudioExtension { get; set; }
        public string FileExtension { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public string InsertUserName { get; set; }
        public string LastUpdateUserName { get; set; }
        public Nullable<int> ActiveComments { get; set; }
        public Nullable<int> InactiveComments { get; set; }
        public string YoutubeCode { get; set; }
        public Nullable<int> RatingCount { get; set; }
        public Nullable<int> RatingValue { get; set; }
        public Nullable<double> GoogleLatitude { get; set; }
        public Nullable<double> GoogleLongitude { get; set; }
        public string Price { get; set; }
        public Nullable<bool> OnlyForRegisered { get; set; }
        public Nullable<bool> PublishPhoto { get; set; }
        public Nullable<bool> PublishPhoto2 { get; set; }
        public Nullable<bool> PublishFile { get; set; }
        public Nullable<bool> PublishAudio { get; set; }
        public Nullable<bool> PublishVideo { get; set; }
        public Nullable<bool> PublishYoutbe { get; set; }
        public Nullable<bool> IsVisitorsParticipations { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string SenderName { get; set; }
        public string SenderEMail { get; set; }
        public Nullable<int> SenderCountryID { get; set; }
        public string Reply { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public Nullable<bool> IsSeen { get; set; }
        public Nullable<bool> IsReplied { get; set; }
        public Nullable<bool> IsReviewed { get; set; }
        public Nullable<System.Guid> ToUserID { get; set; }
        public string ActivatedBy { get; set; }
        public string ReviewedBy { get; set; }
        public Nullable<System.Guid> OwnerID { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> LastModification { get; set; }
        public Nullable<int> RequestTotalCount { get; set; }
        public Nullable<int> RequestNewCount { get; set; }
        public string OwnerName { get; set; }
        public string PropertyNames { get; set; }
        public string PropertyValuesString { get; set; }
        public Nullable<bool> SpecialOption { get; set; }
        public string Icon { get; set; }
        public string Title { get; set; }
        public string AuthorName { get; set; }
        public string Address { get; set; }
        public int LangID { get; set; }
        public string ShortDescription { get; set; }
    }
}
