//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.TestDatalayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMS_AribitationEntities : DbContext
    {
        public CMS_AribitationEntities()
            : base("name=CMS_AribitationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ItemCategories> ItemCategories { get; set; }
        public virtual DbSet<ItemCategoriesDetails> ItemCategoriesDetails { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<ItemsDetails> ItemsDetails { get; set; }
        public virtual DbSet<View_ItemsBaseData> View_ItemsBaseData { get; set; }
    }
}
