//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.TestDatalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsDetails
    {
        public int ItemID { get; set; }
        public int LangID { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string AuthorName { get; set; }
        public string Address { get; set; }
        public string ExtraData { get; set; }
        public string KeyWords { get; set; }
    }
}
