//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GirasDatalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ItemFiles
    {
        public int FileID { get; set; }
        public int ItemID { get; set; }
        public string FileExtension { get; set; }
        public int FileType { get; set; }
        public string InsertUserName { get; set; }
        public string LastUpdateUserName { get; set; }
        public int ModuleTypeID { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> OwnerID { get; set; }
        public string OwnerName { get; set; }
        public string ItemTitle { get; set; }
    }
}
