//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SiteText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن السكينة.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستشارين.
        /// </summary>
        internal static string Advisers {
            get {
                return ResourceManager.GetString("Advisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الخدمات.
        /// </summary>
        internal static string AllServices {
            get {
                return ResourceManager.GetString("AllServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدونة.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اراء عملائنا.
        /// </summary>
        internal static string ClientsVoice {
            get {
                return ResourceManager.GetString("ClientsVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        internal static string ContactFormEmail {
            get {
                return ResourceManager.GetString("ContactFormEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاول.
        /// </summary>
        internal static string ContactFormFirstName {
            get {
                return ResourceManager.GetString("ContactFormFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاخير.
        /// </summary>
        internal static string ContactFormLastName {
            get {
                return ResourceManager.GetString("ContactFormLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اترك رسالتك.
        /// </summary>
        internal static string ContactFormLeaveYourMessage {
            get {
                return ResourceManager.GetString("ContactFormLeaveYourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسالة.
        /// </summary>
        internal static string ContactFormMessage {
            get {
                return ResourceManager.GetString("ContactFormMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        internal static string ContactFormName {
            get {
                return ResourceManager.GetString("ContactFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        internal static string ContactFormSend {
            get {
                return ResourceManager.GetString("ContactFormSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم استلام رسالتك شكراً جزيلا لتوصلك معنا.
        /// </summary>
        internal static string ContactFormSuccessSent {
            get {
                return ResourceManager.GetString("ContactFormSuccessSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبايل.
        /// </summary>
        internal static string ContactMobile {
            get {
                return ResourceManager.GetString("ContactMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان:.
        /// </summary>
        internal static string ContactsAddress {
            get {
                return ResourceManager.GetString("ContactsAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الاتصال.
        /// </summary>
        internal static string ContactsData {
            get {
                return ResourceManager.GetString("ContactsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد:.
        /// </summary>
        internal static string ContactsEmail {
            get {
                return ResourceManager.GetString("ContactsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفاكس:.
        /// </summary>
        internal static string ContactsFax {
            get {
                return ResourceManager.GetString("ContactsFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تواصل معنا.
        /// </summary>
        internal static string ContactsFormCaption {
            get {
                return ResourceManager.GetString("ContactsFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التليفون:.
        /// </summary>
        internal static string ContactsTel {
            get {
                return ResourceManager.GetString("ContactsTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكتب.
        /// </summary>
        internal static string ContactsTheOffice {
            get {
                return ResourceManager.GetString("ContactsTheOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إتصل بنا.
        /// </summary>
        internal static string ContactUS {
            get {
                return ResourceManager.GetString("ContactUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;copy; جميع الحقوق محفوظة لشركة ديجيتال تاجز 2015.
        /// </summary>
        internal static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني:.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسئلة شائعة.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرض الصور.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يشمل نطاق الخدمات المقدمة من مركز جنيف للتحكيم الدولي.
        /// </summary>
        internal static string GenevaServicesIntro {
            get {
                return ResourceManager.GetString("GenevaServicesIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات مركز جنيف.
        /// </summary>
        internal static string GenevaServicesTitle {
            get {
                return ResourceManager.GetString("GenevaServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخبار وفعاليات.
        /// </summary>
        internal static string HomePageNewsTitle {
            get {
                return ResourceManager.GetString("HomePageNewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يقدم مركز جينيف للتحكيم العديد من فرص الدراسات العليا في مجال التحكيم الدولي كدبلوم التحكيم الإلكتروني وصياغة العقود كما يقدم المركزفرصة الحصول على درجة الماجيستير في مجال التحكيم الدولي.
        /// </summary>
        internal static string HomePageStudiesIntro {
            get {
                return ResourceManager.GetString("HomePageStudiesIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يقدم مركز جينيف للتحكيم الدولي العديد من البرامج التدريبية من اجل نشر فكر التحكيم الدولي ورفع كفاءة المحكمين.
        /// </summary>
        internal static string HomePageTrainingIntro {
            get {
                return ResourceManager.GetString("HomePageTrainingIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفنادق.
        /// </summary>
        internal static string Hotels {
            get {
                return ResourceManager.GetString("Hotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LangArabic {
            get {
                return ResourceManager.GetString("LangArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LangEnglish {
            get {
                return ResourceManager.GetString("LangEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احدث الفيديوهات.
        /// </summary>
        internal static string LastVideo {
            get {
                return ResourceManager.GetString("LastVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أحدث العروض.
        /// </summary>
        internal static string LatestOffers {
            get {
                return ResourceManager.GetString("LatestOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جينيف للتحكيم الدولي.
        /// </summary>
        internal static string MenuAbout1 {
            get {
                return ResourceManager.GetString("MenuAbout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نادي جنيف للتحكيم التجاري الدولي.
        /// </summary>
        internal static string MenuAbout2 {
            get {
                return ResourceManager.GetString("MenuAbout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فريق العمل.
        /// </summary>
        internal static string MenuAbout3 {
            get {
                return ResourceManager.GetString("MenuAbout3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجلة جنيف للتحكيم الدولي.
        /// </summary>
        internal static string MenuAbout4 {
            get {
                return ResourceManager.GetString("MenuAbout4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نادي جنيف للتحكيم التجاري الدولي.
        /// </summary>
        internal static string MenuAbout5 {
            get {
                return ResourceManager.GetString("MenuAbout5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوائم المستشارين.
        /// </summary>
        internal static string MenuAbout6 {
            get {
                return ResourceManager.GetString("MenuAbout6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوائح و قوانين جنيف للتحكيم الدولي.
        /// </summary>
        internal static string MenuAbout7 {
            get {
                return ResourceManager.GetString("MenuAbout7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من نحن.
        /// </summary>
        internal static string MenuAboutTitle {
            get {
                return ResourceManager.GetString("MenuAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكتبة الكتب.
        /// </summary>
        internal static string MenuBooks {
            get {
                return ResourceManager.GetString("MenuBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروعنا.
        /// </summary>
        internal static string MenuBraches {
            get {
                return ResourceManager.GetString("MenuBraches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤتمرات.
        /// </summary>
        internal static string MenuConferences {
            get {
                return ResourceManager.GetString("MenuConferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصل بنا.
        /// </summary>
        internal static string MenuContactUs {
            get {
                return ResourceManager.GetString("MenuContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string MenuEnglish {
            get {
                return ResourceManager.GetString("MenuEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرض الصور.
        /// </summary>
        internal static string MenuGallery {
            get {
                return ResourceManager.GetString("MenuGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        internal static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوسائط.
        /// </summary>
        internal static string MenuMultimedia {
            get {
                return ResourceManager.GetString("MenuMultimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدماتنا.
        /// </summary>
        internal static string MenuServices {
            get {
                return ResourceManager.GetString("MenuServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدراسات العليا.
        /// </summary>
        internal static string MenuStudies {
            get {
                return ResourceManager.GetString("MenuStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التدريب.
        /// </summary>
        internal static string MenuTainingTitle {
            get {
                return ResourceManager.GetString("MenuTainingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البرامج التدريبية.
        /// </summary>
        internal static string MenuTraining {
            get {
                return ResourceManager.GetString("MenuTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجلس الامناء.
        /// </summary>
        internal static string MenuTruetees {
            get {
                return ResourceManager.GetString("MenuTruetees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكتبة الفيديو.
        /// </summary>
        internal static string MenuVideos {
            get {
                return ResourceManager.GetString("MenuVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مناسك.
        /// </summary>
        internal static string ModuleManasek {
            get {
                return ResourceManager.GetString("ModuleManasek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مزارات.
        /// </summary>
        internal static string ModuleMazarat {
            get {
                return ResourceManager.GetString("ModuleMazarat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزيد.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العروض.
        /// </summary>
        internal static string Offers {
            get {
                return ResourceManager.GetString("Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string OtherLanguageId {
            get {
                return ResourceManager.GetString("OtherLanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رحــلاتنا.
        /// </summary>
        internal static string OurTrips {
            get {
                return ResourceManager.GetString("OurTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سابقة الاعمال.
        /// </summary>
        internal static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كل الصور.
        /// </summary>
        internal static string PortfolioAllItems {
            get {
                return ResourceManager.GetString("PortfolioAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pull-right.
        /// </summary>
        internal static string PullClass {
            get {
                return ResourceManager.GetString("PullClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث عن.
        /// </summary>
        internal static string SearchFor {
            get {
                return ResourceManager.GetString("SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ... بحث عن.
        /// </summary>
        internal static string SearchForPlaceHolder {
            get {
                return ResourceManager.GetString("SearchForPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدماتنا.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جينيف للتحكيم الدولي.
        /// </summary>
        internal static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;اكتشف العالم مع  &lt;span class=&quot;colortext&quot;&gt;السكينة للسياحة&lt;/span&gt; &lt;/h1&gt;.
        /// </summary>
        internal static string SiteSlogan {
            get {
                return ResourceManager.GetString("SiteSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نادي جنيف للتحكيم التجاري الدولي.
        /// </summary>
        internal static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحلول.
        /// </summary>
        internal static string Solutions {
            get {
                return ResourceManager.GetString("Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشرفون.
        /// </summary>
        internal static string Supervisors {
            get {
                return ResourceManager.GetString("Supervisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التليفون :.
        /// </summary>
        internal static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فيديوهات.
        /// </summary>
        internal static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفاصيل.
        /// </summary>
        internal static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WelcomeBoxTitle {
            get {
                return ResourceManager.GetString("WelcomeBoxTitle", resourceCulture);
            }
        }
    }
}
